---
- name: Import Google, Microsoft, and RPM Fusion keys.
  rpm_key:
    key: "{{ item }}"
    state: present
  loop: "{{ keys }}"

- name: Add VS Code Repo.
  yum_repository:
      name: vscode
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgcheck: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      
- name: Add rpmfusion repo.
  dnf: "name=https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-\
    {{ ansible_distribution_major_version }}.noarch.rpm"

- name: Add fedora-workstation-repositories.
  dnf: name=fedora-workstation-repositories state=present

- name: Enable rpmfusion-nonfree-steam
  command: dnf config-manager --set-enabled rpmfusion-nonfree-steam