---
- name: Add users.
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    comment: "{{ item.full_name }}"
    groups: "{{ item.groups }}"
    append: yes
  loop: "{{ users }}"
